sequenceDiagram
  actor A1 as User
  participant API as Presentation (API)
  participant BusinessLogic
  participant Persistence as Persistence (Database)


A1 ->> API: User Register Request (first_name, last_name, email, password)
Note over API: Validate and Process Request 
API ->> BusinessLogic: Forward Register Request 
Note over BusinessLogic: Hash password, Generate UUID, Create Time
BusinessLogic ->> Persistence: Save user data (ID, first_name, last_name, email, hach_password, created_at, update_at)
Persistence -->> BusinessLogic: Confirm Save, return new user ID
BusinessLogic -->> API: Return Respons (Without password)
API -->> A1: Return Message (Success or Failed)
